config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # LISTS
  root 'lists#index'
  resources :lists do
    resources :bookmarks, only: %i[new create]
    resources :reviews, only: %i[new create]
  end

  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]
  def index
    @lists = List.all
  end

  def show; end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to root_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_list, only: %i[new create]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.list = @list
    @review.save
    redirect_to list_path(@list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<div class="banner">
  <h1>Save a movie to your list</h1>
  <h2>You are on the <%= @list.name %> List</h2>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-6 py-5">
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.association :movie %>
        <%= f.input :comment %>
        <%= f.button :submit, class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div id="home">
  <div class="banner">
    <h1>Save any kind of movies</h1>
  </div>

  <div class="container py-5">
    <div class="row">
      <div class="col-8">
       <h2>My Lists</h2>
        <div class="row justify-content-center align-items-center">
          <% @lists.each do |list| %>
            <div class="col-5 list_card m-1" style='background-image: url("<%= cl_image_path list.photo.key, height: 300, crop: :fill %>")'>
            <%= link_to list.name, list_path(list) %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-4">
        <%= link_to "Create a Movie List", new_list_path, class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="banner">
  <h1>Create a New Movie List</h1>
</div>

<div class="container py-5">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for(@list) do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: 'btn btn-success'%>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner show-page" style="background-image: url(<%= cl_image_path @list.photo.key%>)">
  <h1>View Movies in the <%= @list.name %> List </h1>
</div>

<div class="container py-2">
  <div class="row align-items-end flex-column">
    <%= link_to "Add a Movie", new_list_bookmark_path(@list), class: 'btn btn-success m-1 add-button' %>
    <%= link_to "Add a Review", new_list_review_path(@list), class: 'btn btn-primary m-1 add-button' %>
  </div>
  <div class="row">
    <% @list.reviews.each do |review| %>
      <div class="col-6">
      <h3><%= review.content %></h3>
      </div>
    <% end %>
  </div>
  <div class="row py-5">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="col-3 movie-card m-2">
      <%= image_tag bookmark.movie.poster_url %>
      <div class="content">
        <h2 class="py-3"><%= bookmark.movie.title %> . <%= bookmark.movie.rating %> . <i class="fas fa-star"></i></h2> 
        <p><%= bookmark.movie.overview %></p>
        <h3 class="py-3"><i class="fas fa-quote-left mr-3"></i><%= bookmark.comment %></h3>
        <div class="row justify-content-end">
          <%= link_to "Delete", bookmark_path(bookmark), method: :delete, class: 'mb-3 mr-3 btn-sm btn btn-danger', data: {confirm: "Are you sure?"}  %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="banner">
  <h1>Create a New Review for <%= @list.name %> List </h1>
</div>

<div class="container py-5">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for [@list, @review] do |f| %>
        <%= f.input :content %>
        <%= f.button :submit, class: 'btn btn-success'%>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://image.flaticon.com/icons/png/512/433/433461.png" %>
      <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "My Lists", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "New Lists", new_list_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>  